spring:
  jpa:
    database: "MYSQL"
    show-sql: "true"
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL5Dialect"
  datasource:
    platform: "mysql"
    url: "jdbc:mysql://192.168.99.101:3306/javatest?autoReconnect=true"
    username: "sanghl87"
    password: "0ffended"
    test-while-idle: "true"
    validationQuery: "SELECT 1"
    driverClassName: "com.mysql.cj.jdbc.Driver"